// <auto-generated />
using System;
using Fungry.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fungry.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240318033044_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fungry.API.Data.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://serenetrail.com/wp-content/uploads/2022/11/A-slice-of-bbq-pizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 15.199999999999999
                        });
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.FoodOption", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Taste")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Extra")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FoodId", "Taste", "Extra");

                    b.ToTable("FoodOptions");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Taste = "Default",
                            Extra = "Cheese"
                        },
                        new
                        {
                            FoodId = 2,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 3,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 4,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 5,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 6,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 7,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 8,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 9,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 10,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 11,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 12,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 13,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 14,
                            Taste = "Spicy",
                            Extra = "Default"
                        },
                        new
                        {
                            FoodId = 15,
                            Taste = "Spicy",
                            Extra = "Default"
                        });
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Extra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Taste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.user", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.FoodOption", b =>
                {
                    b.HasOne("Fungry.API.Data.Entities.Food", "Food")
                        .WithMany("Options")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("Fungry.API.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.Food", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Fungry.API.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
